[package]
name = "nextjlc-core"
version = "0.1.3"
edition = "2024"

[lib]
path = "src/lib.rs"
crate-type = ["lib"]

[dependencies]
rand = "0.9"
chrono = "0.4"
md-5 = "0.10"
regex = "1"
fancy-regex = "0.16"
once_cell = "1"